export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = ' REMOVE_ALERT'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const USER_LOADED = 'USER_LOADED'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGOUT = 'LOGOUT'

export const GET_USER = 'GET_USER'
export const GET_USERS = 'GET_USERS'
export const UPDATE_USER = 'UPDATE_USER'
export const POST_ERROR = 'POST_ERROR'

export const GET_PLACES = 'GET_PLACES'
export const GET_PLACE = 'GET_PLACE'
export const ADD_PLACE = 'ADD_PLACE'
export const DELETE_PLACE = 'DELETE_PLACE'
export const UPDATE_PLACE = 'UPDATE_PLACE'
export const RATE_PLACE = 'RATE_PLACE'
export const COMMENT_PLACE = 'COMMENT_PLACE'
export const DELETE_COMMENT_PLACE = 'DELETE_COMMENT_PLACE'

export const FOLLOW_USER = 'FOLLOW_USER'
export const UNFOLLOW_USER = 'UNFOLLOW_USER'
export const DELETE_FOLLOWER = 'DELETE_FOLLOWER'
export const ADD_PLACE_WL = 'ADD_PLACE_WL'
export const DELETE_PLACE_WL = 'DELETE_PLACE_WL'
export const UPDATE_PLACE_WL = 'UPDATE_PLACE_WL'

export const ADD_BOARD = 'ADD_BOARD'
export const UPDATE_BOARD = 'UPDATE_BOARD'
export const DELETE_BOARD = 'DELETE_BOARD'
export const GET_BOARD = 'GET_BOARD'
export const GET_BOARDS = 'GET_BOARDS'
export const FOLLOW_BOARD = 'FOLLOW_BOARD'
export const UNFOLLOW_BOARD = 'UNFOLLOW_BOARD'
export const ADD_PLACE_B = 'ADD_PLACE_B'
export const DELETE_PLACE_B = 'DELETE_PLACE_B'
